

# Примерно так должен выглядеть ваш код в application.yml:
spring:
  cloud:
    gateway:
      routes:
        - id: Proxy # Строка, примерно соответствующая вашей ошибке
          uri: ${BACKEND_URL}
          predicates:
            - Path=/api/send-message
          # Добавьте другие поля, если они есть (filters, etc.)